### ISSUE TITLE
Background task is run with each iteration of Scenario Outline

### ISSUE THREAD

**Issue by dadamschi** [gfk-ba/senbot#18]
I am testing the following feature. 

Feature: Test A Logged In User
This is a feature that tests a logged in user

  Background: Navigate to start page for all scenarios
    Given I am logged in as a "student" user

  Scenario Outline: The navigation links are on the page
    When I click on the link with name "<name>"
    Then the Cappex page title is "<page_title>"

  Examples: link result pairs
    |  name  |     page_title       |
    | Dashboard | Student Dashboard |
    | Colleges | College Center | Cappex |
    | Visits | Campus Visit Planner - My Trips | Cappex |

The code logs in my user but when clicking on the links, the user is logged in again (goes to the log in page and submits the log in form).

My expectation is that the user would get logged in and the links would just be clicked without anything in between.

Is this a generic Cucumber question?

**Comment by joostschouten** [comment]
Yes, this is indeed a Cucumber question best asked on stackoverflow, or when it concerns the source code and you think there might be a bug or room for improvement, [cucumber-jvm](https://github.com/cucumber/cucumber-jvm]) is where to look as we use it internally for parsing and execution of cucumber.

Having said that, what you are seeing is expected and how it should be. A "Scenario Outline" acts as a scenario template where each example will in fact be seen as a separate scenario. And since background will be run before each scenario, it will be run before each example as well.
